/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab11_problem1;

import java.awt.Color;

/**
 *
 * @author Kevin Brenneman
 */
public class Lab11 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Lab11() {
        initComponents();
        //set the initial color for all of the background elements
        getContentPane().setBackground(Color.GREEN);
        jRadioButtonBlue.setBackground(Color.GREEN);
        jRadioButtonGreen.setBackground(Color.GREEN);
        jRadioButtonYellow.setBackground(Color.GREEN);
        jRadioButtonCyan.setBackground(Color.GREEN);
        jTextField1.setBackground(Color.GREEN);
        jTextField2.setBackground(Color.GREEN);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTextField1 = new javax.swing.JTextField();
        jRadioButtonGreen = new javax.swing.JRadioButton();
        jRadioButtonYellow = new javax.swing.JRadioButton();
        jRadioButtonBlue = new javax.swing.JRadioButton();
        jRadioButtonCyan = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPasswordField1.setText("jPasswordField1");

        jTextField1.setEditable(false);
        jTextField1.setText("Non-Editable Text");
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonGreen);
        jRadioButtonGreen.setSelected(true);
        jRadioButtonGreen.setText("Green");
        jRadioButtonGreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonGreenActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonYellow);
        jRadioButtonYellow.setText("Yellow");
        jRadioButtonYellow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonYellowActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonBlue);
        jRadioButtonBlue.setText("Blue");
        jRadioButtonBlue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonBlueActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonCyan);
        jRadioButtonCyan.setText("Cyan");
        jRadioButtonCyan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCyanActionPerformed(evt);
            }
        });

        jButton1.setText("Show password");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField2.setEditable(false);
        jTextField2.setText("Background Color");
        jTextField2.setBorder(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jRadioButtonBlue)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRadioButtonCyan))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jRadioButtonGreen)
                            .addGap(18, 18, 18)
                            .addComponent(jRadioButtonYellow))))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(4, 4, 4)
                            .addComponent(jButton1)))
                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonGreen)
                            .addComponent(jRadioButtonYellow))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonBlue)
                            .addComponent(jRadioButtonCyan))))
                .addGap(5, 5, 5)
                .addComponent(jButton1)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //uneeded generated by netbeans on accident
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed
    //sets jtextfield1 equal to the text that is in the 
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jTextField1.setText(jPasswordField1.getText());
    }//GEN-LAST:event_jButton1ActionPerformed
    //listner for whenever the user selects blue
    private void jRadioButtonBlueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonBlueActionPerformed
        getContentPane().setBackground(Color.BLUE);
        jRadioButtonBlue.setBackground(Color.BLUE);
        jRadioButtonGreen.setBackground(Color.BLUE);
        jRadioButtonYellow.setBackground(Color.BLUE);
        jRadioButtonCyan.setBackground(Color.BLUE);
        jTextField1.setBackground(Color.BLUE);
        jTextField2.setBackground(Color.BLUE);
    }//GEN-LAST:event_jRadioButtonBlueActionPerformed
    //listner for whenever the user selects green
    private void jRadioButtonGreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonGreenActionPerformed
        getContentPane().setBackground(Color.GREEN);
        jRadioButtonBlue.setBackground(Color.GREEN);
        jRadioButtonGreen.setBackground(Color.GREEN);
        jRadioButtonYellow.setBackground(Color.GREEN);
        jRadioButtonCyan.setBackground(Color.GREEN);
        jTextField1.setBackground(Color.GREEN);
        jTextField2.setBackground(Color.GREEN);
    }//GEN-LAST:event_jRadioButtonGreenActionPerformed
    //listner for whenever the user selects yellow
    private void jRadioButtonYellowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonYellowActionPerformed
        getContentPane().setBackground(Color.YELLOW);
        jRadioButtonBlue.setBackground(Color.YELLOW);
        jRadioButtonGreen.setBackground(Color.YELLOW);
        jRadioButtonYellow.setBackground(Color.YELLOW);
        jRadioButtonCyan.setBackground(Color.YELLOW);
        jTextField1.setBackground(Color.YELLOW);
        jTextField2.setBackground(Color.YELLOW);
    }//GEN-LAST:event_jRadioButtonYellowActionPerformed
    //listner for whenever the user selects cyan
    private void jRadioButtonCyanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCyanActionPerformed
        getContentPane().setBackground(Color.CYAN);
        jRadioButtonBlue.setBackground(Color.CYAN);
        jRadioButtonGreen.setBackground(Color.CYAN);
        jRadioButtonYellow.setBackground(Color.CYAN);
        jRadioButtonCyan.setBackground(Color.CYAN);
        jTextField1.setBackground(Color.CYAN);
        jTextField2.setBackground(Color.CYAN);
    }//GEN-LAST:event_jRadioButtonCyanActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lab11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lab11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lab11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lab11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lab11().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JRadioButton jRadioButtonBlue;
    private javax.swing.JRadioButton jRadioButtonCyan;
    private javax.swing.JRadioButton jRadioButtonGreen;
    private javax.swing.JRadioButton jRadioButtonYellow;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
